---
version: '3.9'
services:
  hackbox:
    image: hackbox:latest
    container_name: hackbox
    ports:
      - 4444:4444
    volumes: 
      - /D/Coding/HackboxWorkspace/bundles:/bundles
      - /D/Coding/HackboxWorkspace/mods:/mods
